### ISSUE TITLE
When I run to around 1500 rounds, I get an error like this

### ISSUE THREAD

**Issue by FADEAWAY114** [federicovergallo/SUMO-changing-lane-agent#17]
When I run to around 1500 rounds, I get an error like this
![55](https://user-images.githubusercontent.com/105548396/227555906-a1986374-f63d-460d-acac-c2ef4bd7826e.png)

**`2023-03-24 22:01:09.380560: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at sparse_xent_op.cc:90 : Invalid argument: Received a label value of 3 which is outside the valid range of [0, 3).  Label values: 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
Traceback (most recent call last):
  File "/home/vmware/桌面/SUMO-changing-lane-agent-master/test.py", line 10, in <module>
    agent.train(env)
  File "/home/vmware/桌面/SUMO-changing-lane-agent-master/a2c.py", line 136, in train
    losses = self.model.train_on_batch(observations, [acts_and_advs, returns])
  File "/home/vmware/anaconda3/envs/changelane2/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1727, in train_on_batch
    logs = self.train_function(iterator)
  File "/home/vmware/anaconda3/envs/changelane2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/vmware/anaconda3/envs/changelane2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 862, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/vmware/anaconda3/envs/changelane2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/vmware/anaconda3/envs/changelane2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/vmware/anaconda3/envs/changelane2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/home/vmware/anaconda3/envs/changelane2/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Received a label value of 3 which is outside the valid range of [0, 3).  Label values: 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
	 [[node logits_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits (defined at /桌面/SUMO-changing-lane-agent-master/a2c.py:199) ]] [Op:__inference_train_function_9631]

Function call stack:
train_function`**

**Comment by sunnystarh** [comment]
[FADEAWAY114]，你好我最近也在跑这个代码，我跑的时候好像没出现这个问题，可以加个好友沟通吗

**Comment by FADEAWAY114** [comment]
> [FADEAWAY114]，你好我最近也在跑这个代码，我跑的时候好像没出现这个问题，可以加个好友沟通吗

Of course

**Comment by sunnystarh** [comment]
qq：541033556

**Comment by SHITIANYU-hue** [comment]
i also have this error

**Comment by yaoleyaotououo** [comment]
> > [FADEAWAY114]，你好我最近也在跑这个代码，我跑的时候好像没出现这个问题，可以加个好友沟通吗
> 
> Of course

可以加个QQ吗，最近也在跑这个代码，但跑不起来

**Comment by xbv001** [comment]
> > > [FADEAWAY114]，你好我最近也在跑这个代码，我跑的时候好像没出现这个问题，可以加个好友沟通吗
> > 
> > 
> > Of course
> 
> 可以加个QQ吗，最近也在跑这个代码，但跑不起来

Hi, have you made it? I also encountered the same problem.

**Comment by SHITIANYU-hue** [comment]
可以加个微信群😂

**Comment by xbv001** [comment]
> 可以加个微信群😂
快！大佬拉一个

**Comment by SHITIANYU-hue** [comment]
哪个大佬发个微信群截图？

**Comment by youying12123** [comment]
I have the same error.

**Comment by xulw8** [comment]
> > > [FADEAWAY114]，你好我最近也在跑这个代码，我跑的时候好像没出现这个问题，可以加个好友沟通吗
> > 
> > 
> > Of course
> 
> 可以加个QQ吗，最近也在跑这个代码，但跑不起来

你好我也遇到这个问题，想请教一下大佬
